### ISSUE TITLE
The result printing of DnC is not consistent with the single-solver printing

### ISSUE THREAD

**Issue by ahmed-irfan** [guykatzz/Marabou#154]
when running DnC mode, the result is not printed in the same as how the single-solver mode prints

Single solver mode
```
...
	--- Basis Factorization statistics ---
	Number of basis refactorizations: 1340
	--- Projected Steepest Edge Statistics ---
	Number of iterations: 72560.
	Number of resets to reference space: 754. Avg. iterations per reset: 96
	--- SBT ---
	Number of tightened bounds: 29115
UNSAT
```

DnC solver mode
```
...
Worker 1: Query 6-15 UNSAT, 3 tasks remaining
Worker 0: Query 6-16 UNSAT, 2 tasks remaining
Worker 3: Query 6-8 UNSAT, 1 tasks remaining
DnCManager::solve UNSAT query
Total Time: 19
```

**Comment by yuvaljacoby** [comment]
Hey,
Since you didn't merge this yet, and I found that we are not align in another place (mps_parser) can you apply the attached patch before merging? (it's not a zip file just changed the extension so github will let me upload)
[0001-algin-prints.zip](https://github.com/guykatzz/Marabou/files/3710327/0001-algin-prints.zip)
